
CREATE TABLE NDC (
    id INTEGER PRIMARY KEY,
    RXCUI VARCHAR(32),
    NDC_DIGITS VARCHAR(32),
    -- NDC11 VARCHAR(32),
    -- XML_FILENAME VARCHAR(32),
    PDF_FILENAME VARCHAR(32),
    IMG_FILENAME VARCHAR(32),
    UNIQUE(NDC_DIGITS) ON CONFLICT REPLACE
);
CREATE INDEX ndc_idx       ON NDC (NDC_DIGITS);
CREATE INDEX ndc_rxcui_idx ON NDC (RXCUI);
-- CREATE INDEX ndc11_idx ON NDC (NDC11);

CREATE TABLE RxTerms (
    id INTEGER PRIMARY KEY,
    RXCUI VARCHAR(32),
    RxNormName VARCHAR(1024),
    MDDB_ID VARCHAR(1024),
    FULL_NAME VARCHAR(1024),
    RXN_DOSE_FORM VARCHAR(1024),
    FULL_GENERIC_NAME VARCHAR(1024),
    BRAND_NAME VARCHAR(1024),
    DISPLAY_NAME VARCHAR(1024),
    ROUTE VARCHAR(1024),
    NEW_DOSE_FORM VARCHAR(1024),
    STRENGTH VARCHAR(1024),
    SXDG_NAME VARCHAR(1024),
    SEARCH_STR VARCHAR(1024)
);
CREATE INDEX rxterms_rxcui_idx ON RxTerms (RXCUI);
CREATE INDEX rxterms_idx       ON RxTerms (SEARCH_STR);



