
CREATE TABLE RXNSAT (
    id INTEGER PRIMARY KEY,
    RXCUI VARCHAR(1024),
    LUI VARCHAR(1024),
    SUI VARCHAR(1024),
    RXAUI VARCHAR(1024),
    STYPE VARCHAR(1024),
    CODE VARCHAR(1024),
    ATUI VARCHAR(1024),
    SATUI VARCHAR(1024),
    ATN VARCHAR(1024),
    SAB VARCHAR(1024),
    ATV VARCHAR(1024),
    SUPPRESS VARCHAR(1024),
    CVF  VARCHAR(1024)
);


CREATE TABLE RXNCONSO (
    id INTEGER PRIMARY KEY,
    RXCUI VARCHAR(1024),
    LAT VARCHAR(1024),
    TS VARCHAR(1024),
    LUI VARCHAR(1024),
    STT VARCHAR(1024),
    SUI VARCHAR(1024),
    ISPREF VARCHAR(1024),
    RXAUI VARCHAR(1024),
    SAUI VARCHAR(1024),
    SCUI VARCHAR(1024),
    SDUI VARCHAR(1024),
    SAB VARCHAR(1024),
    TTY VARCHAR(1024),
    CODE VARCHAR(1024),
    STR VARCHAR(1024),
    SRL VARCHAR(1024),
    SUPPRESS VARCHAR(1024),
    CVF  VARCHAR(1024)
);
CREATE INDEX rxnconso_rxcui_idx ON RXNCONSO (RXCUI);

CREATE TABLE RXTERMS (
    id INTEGER PRIMARY KEY,
    RXCUI VARCHAR(1024),
    GENERIC_RXCUI VARCHAR(1024),
    TTY VARCHAR(1024),
    FULL_NAME VARCHAR(1024),
    RXN_DOSE_FORM VARCHAR(1024),
    FULL_GENERIC_NAME VARCHAR(1024),
    BRAND_NAME VARCHAR(1024),
    DISPLAY_NAME VARCHAR(1024),
    ROUTE VARCHAR(1024),
    NEW_DOSE_FORM VARCHAR(1024),
    STRENGTH VARCHAR(1024),
    SUPPRESS_FOR VARCHAR(1024),
    DISPLAY_NAME_SYNONYM VARCHAR(1024),
    IS_RETIRED VARCHAR(1024),
    SXDG_RXCUI VARCHAR(1024),
    SXDG_TTY VARCHAR(1024),
    SXDG_NAME VARCHAR(1024)
);
CREATE INDEX rxterms_rxcui_idx ON RXTERMS (RXCUI);



CREATE TABLE IMMCNCPT (
    id INTEGER PRIMARY KEY,
    ConceptID VARCHAR(16),
    NDC11 VARCHAR(16)
);
CREATE INDEX IMMCNCPT_idx ON IMMCNCPT (NDC11);

CREATE TABLE IMMLINK (
    id INTEGER PRIMARY KEY,
    ConceptID VARCHAR(16),
    ContentType VARCHAR(16),
    Filename VARCHAR(32)
);
CREATE INDEX IMMLINK_idx ON IMMLINK (ConceptID);

CREATE TABLE IM2UDRUG (
    id INTEGER PRIMARY KEY,
    DrugID VARCHAR(16),
    NDC11 VARCHAR(16)
);
CREATE INDEX IM2UDRUG_idx ON IM2UDRUG (NDC11);

CREATE TABLE IM2UDIJ (
    id INTEGER PRIMARY KEY,
    DrugID VARCHAR(16),
    ImageID VARCHAR(16)
);
CREATE INDEX IM2UDIJ_idx ON IM2UDIJ (DrugID);

CREATE TABLE IM2IMG (
    id INTEGER PRIMARY KEY,
    ImageID VARCHAR(16),
    Filename VARCHAR(32)
);
CREATE INDEX IM2IMG_idx ON IM2IMG (ImageID);



